### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by bevinthomas** [KjellConnelly/react-native-musicplayercontroller#1]
It shows a blank screen and then an alert cancel popup.

MusicPlayerController.presentPicker((metadata)=>{
      // Successfully saved MPMediaItemCollection to NSUserDefaults.
      //    Returns an array of metadata for each track (not all MPMediaItem
      //    fields are copied, only the blantantly needed ones)
        alert(metadata[0]["title"])
    }, ()=>{
      // Opened, but user tapped Cancel
      alert("Cancel")
    })

**Comment by ananyacleetus** [comment]
Were you able to figure this out? I'm having the same issue
