### ISSUE TITLE
react-native-musicplayercontroller:compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by lancer1993** [KjellConnelly/react-native-musicplayercontroller#6]
I got the below exception after installing the react-native-musicplayercontroller library. 

F:\Zincat\extra resource works\MusicPlayerExample\node_modules\react-native-musicplayercontroller\android\src\main\java\com\reactlibrary\RNReactNativeMusicplayercontrollerPackage.java:19: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error

FAILURE: Build failed with an exception

**Comment by KjellConnelly** [comment]
I think the android API got updated, so I can't use @override there anymore. Feel free to look for an alternative, though I haven't/won't be working with Android personally for awhile.

**Comment by KjellConnelly** [comment]
@lancer1993 Hey, I finally got around to working on RN app and got the same error you had. So I removed the @override line and now it works. New version on npm.
